-- Migration: Seed lote 6 (5 processos)
-- Esta migration executa a função seed_single_process para um lote de processos

DO $$
DECLARE
    v_process_id UUID;
BEGIN
    SELECT seed_single_process(
        'Falta de Energia',
        'emergencias',
        'manual',
        'em_revisao',
        'Procedimento para situações de falta de energia elétrica, incluindo verificação, comunicação e acionamento de serviços.',
        '{"description": "Procedimento para situações de falta de energia elétrica, incluindo verificação, comunicação e acionamento de serviços.", "workflow": ["1. Identificação da falta de energia", "2. Verificação se é problema local ou geral", "3. Comunicação à portaria/síndico", "4. Verificação de disjuntores e sistema elétrico", "5. Acionamento da concessionária se necessário", "6. Comunicação aos moradores", "7. Acompanhamento até resolução", "8. Verificação de funcionamento após retorno", "9. Registro do incidente"], "entities": ["Moradores", "Síndico", "Concessionária de Energia", "Portaria Online"], "variables": ["telefone_concessionaria"], "mermaid_diagram": "flowchart TD\n    A[\"Identificação da Falta<br/>(Moradores)\"] --> B{Problema Local ou Geral?}\n    B -->|Local| C[\"Verificação de Disjuntores<br/>(Moradores)\"]\n    B -->|Geral| D[\"Comunicação à Portaria<br/>(Moradores)\"]\n    C --> E{Resolvido?}\n    E -->|Sim| F[\"Verificação de Funcionamento<br/>(Moradores)\"]\n    E -->|Não| D\n    D --> G[\"Acionamento Concessionária<br/>(Síndico)\"]\n    G --> H[\"Comunicação aos Moradores<br/>(Portaria Online)\"]\n    H --> I[\"Acompanhamento<br/>(Síndico)\"]\n    I --> J[\"Retorno da Energia<br/>(Concessionária)\"]\n    J --> F\n    F --> K[\"Registro do Incidente<br/>(Portaria Online)\"]\n    style A fill:#dc2626,stroke:#ef4444,color:#fff\n    style C fill:#1e3a8a,stroke:#3b82f6,color:#fff\n    style D fill:#1e3a8a,stroke:#3b82f6,color:#fff\n    style G fill:#dc2626,stroke:#ef4444,color:#fff\n    style H fill:#1e3a8a,stroke:#3b82f6,color:#fff\n    style I fill:#166534,stroke:#22c55e,color:#fff\n    style J fill:#166534,stroke:#22c55e,color:#fff\n    style F fill:#166534,stroke:#22c55e,color:#fff\n    style K fill:#166534,stroke:#22c55e,color:#fff"}'::jsonb,
        '["Moradores", "Síndico", "Concessionária de Energia", "Portaria Online"]'::jsonb,
        '{"telefone_concessionaria": null}'::jsonb
    ) INTO v_process_id;
    SELECT seed_single_process(
        'Elevador Preso',
        'emergencias',
        'manual',
        'em_revisao',
        'Procedimento de emergência para situações de pessoas presas no elevador, incluindo acionamento de socorro e resgate.',
        '{"description": "Procedimento de emergência para situações de pessoas presas no elevador, incluindo acionamento de socorro e resgate.", "workflow": ["1. Identificação de pessoas presas no elevador", "2. Acionamento do botão de emergência", "3. Comunicação com portaria/síndico", "4. Acionamento imediato da empresa de manutenção", "5. Tranquilização das pessoas presas", "6. Acompanhamento até resgate", "7. Verificação de condições das pessoas resgatadas", "8. Acionamento de serviços médicos se necessário", "9. Bloqueio do elevador até reparo", "10. Registro do incidente"], "entities": ["Moradores", "Empresa de Manutenção dos Elevadores", "Síndico", "Portaria Online"], "variables": ["empresa_elevador", "telefone_samu"], "mermaid_diagram": "flowchart TD\n    A[\"Identificação de Pessoas Presas<br/>(Moradores)\"] --> B[\"Botão de Emergência<br/>(Pessoas Presas)\"]\n    B --> C[\"Comunicação Portaria/Síndico<br/>(Pessoas Presas)\"]\n    C --> D[\"Acionamento Empresa Manutenção<br/>(Portaria Online)\"]\n    D --> E[\"Tranquilização das Pessoas<br/>(Portaria Online)\"]\n    E --> F[\"Acompanhamento<br/>(Síndico)\"]\n    F --> G[\"Resgate<br/>(Empresa de Manutenção)\"]\n    G --> H{Necessita Atendimento Médico?}\n    H -->|Sim| I[\"Acionamento SAMU<br/>(Síndico)\"]\n    H -->|Não| J[\"Verificação de Condições<br/>(Síndico)\"]\n    I --> J\n    J --> K[\"Bloqueio do Elevador<br/>(Portaria Online)\"]\n    K --> L[\"Reparo<br/>(Empresa de Manutenção)\"]\n    L --> M[\"Registro do Incidente<br/>(Portaria Online)\"]\n    style A fill:#dc2626,stroke:#ef4444,color:#fff\n    style B fill:#dc2626,stroke:#ef4444,color:#fff\n    style C fill:#dc2626,stroke:#ef4444,color:#fff\n    style D fill:#dc2626,stroke:#ef4444,color:#fff\n    style E fill:#1e3a8a,stroke:#3b82f6,color:#fff\n    style F fill:#166534,stroke:#22c55e,color:#fff\n    style G fill:#1e3a8a,stroke:#3b82f6,color:#fff\n    style I fill:#dc2626,stroke:#ef4444,color:#fff\n    style J fill:#166534,stroke:#22c55e,color:#fff\n    style K fill:#dc2626,stroke:#ef4444,color:#fff\n    style L fill:#1e3a8a,stroke:#3b82f6,color:#fff\n    style M fill:#166534,stroke:#22c55e,color:#fff"}'::jsonb,
        '["Moradores", "Empresa de Manutenção dos Elevadores", "Síndico", "Portaria Online"]'::jsonb,
        '{"empresa_elevador": null, "telefone_samu": null}'::jsonb
    ) INTO v_process_id;
    SELECT seed_single_process(
        'Ameaça à Segurança',
        'emergencias',
        'manual',
        'em_revisao',
        'Procedimento de emergência para situações de ameaça à segurança (roubo, agressão, invasão), incluindo acionamento de polícia e medidas de segurança.',
        '{"description": "Procedimento de emergência para situações de ameaça à segurança (roubo, agressão, invasão), incluindo acionamento de polícia e medidas de segurança.", "workflow": ["1. Identificação da ameaça", "2. Acionamento imediato da polícia (190)", "3. Acionamento da empresa de segurança", "4. Isolamento da área se possível", "5. Proteção de evidências", "6. Comunicação ao síndico", "7. Aguardar chegada da polícia", "8. Fornecer informações e evidências", "9. Acompanhamento do caso", "10. Reforço de medidas de segurança se necessário", "11. Registro detalhado do incidente"], "entities": ["Moradores", "Polícia", "Empresa de Segurança", "Síndico", "Portaria Online"], "variables": ["telefone_policia", "empresa_seguranca_rua"], "mermaid_diagram": "flowchart TD\n    A[\"Identificação da Ameaça<br/>(Moradores)\"] --> B[\"Acionamento Polícia 190<br/>(Moradores/Portaria)\"]\n    B --> C[\"Acionamento Segurança<br/>(Portaria Online)\"]\n    C --> D{Isolar Área Possível?}\n    D -->|Sim| E[\"Isolamento<br/>(Portaria Online)\"]\n    D -->|Não| F[\"Proteção de Evidências<br/>(Portaria Online)\"]\n    E --> F\n    F --> G[\"Comunicação ao Síndico<br/>(Portaria Online)\"]\n    G --> H[\"Aguardar Polícia<br/>(Todos)\"]\n    H --> I[\"Fornecer Informações<br/>(Síndico)\"]\n    I --> J[\"Acompanhamento do Caso<br/>(Síndico)\"]\n    J --> K{Reforço Necessário?}\n    K -->|Sim| L[\"Reforço de Segurança<br/>(Empresa de Segurança)\"]\n    K -->|Não| M[\"Registro Detalhado<br/>(Portaria Online)\"]\n    L --> M\n    style A fill:#dc2626,stroke:#ef4444,color:#fff\n    style B fill:#dc2626,stroke:#ef4444,color:#fff\n    style C fill:#dc2626,stroke:#ef4444,color:#fff\n    style E fill:#dc2626,stroke:#ef4444,color:#fff\n    style F fill:#dc2626,stroke:#ef4444,color:#fff\n    style G fill:#1e3a8a,stroke:#3b82f6,color:#fff\n    style H fill:#1e3a8a,stroke:#3b82f6,color:#fff\n    style I fill:#166534,stroke:#22c55e,color:#fff\n    style J fill:#166534,stroke:#22c55e,color:#fff\n    style L fill:#dc2626,stroke:#ef4444,color:#fff\n    style M fill:#166534,stroke:#22c55e,color:#fff"}'::jsonb,
        '["Moradores", "Polícia", "Empresa de Segurança", "Síndico", "Portaria Online"]'::jsonb,
        '{"telefone_policia": null, "empresa_seguranca_rua": null}'::jsonb
    ) INTO v_process_id;
    SELECT seed_single_process(
        'Emergências Médicas',
        'emergencias',
        'manual',
        'em_revisao',
        'Procedimento de emergência para situações médicas urgentes, incluindo acionamento de SAMU, primeiros socorros e apoio.',
        '{"description": "Procedimento de emergência para situações médicas urgentes, incluindo acionamento de SAMU, primeiros socorros e apoio.", "workflow": ["1. Identificação da emergência médica", "2. Acionamento imediato do SAMU (192)", "3. Prestação de primeiros socorros se capacitado", "4. Comunicação à portaria/síndico", "5. Preparação do acesso para ambulância", "6. Acompanhamento até chegada do SAMU", "7. Fornecimento de informações aos paramédicos", "8. Apoio e acompanhamento conforme necessário", "9. Registro do incidente"], "entities": ["Moradores", "SAMU", "Síndico", "Portaria Online"], "variables": ["telefone_samu", "ponto_encontro_ambulancia"], "mermaid_diagram": "flowchart TD\n    A[\"Identificação da Emergência<br/>(Moradores)\"] --> B[\"Acionamento SAMU 192<br/>(Moradores)\"]\n    B --> C{Capacitado para Primeiros Socorros?}\n    C -->|Sim| D[\"Prestação de Primeiros Socorros<br/>(Moradores)\"]\n    C -->|Não| E[\"Comunicação Portaria/Síndico<br/>(Moradores)\"]\n    D --> E\n    E --> F[\"Preparação do Acesso<br/>(Portaria Online)\"]\n    F --> G[\"Aguardar SAMU<br/>(Todos)\"]\n    G --> H[\"Fornecimento de Informações<br/>(Síndico)\"]\n    H --> I[\"Apoio e Acompanhamento<br/>(Síndico)\"]\n    I --> J[\"Registro do Incidente<br/>(Portaria Online)\"]\n    style A fill:#dc2626,stroke:#ef4444,color:#fff\n    style B fill:#dc2626,stroke:#ef4444,color:#fff\n    style D fill:#dc2626,stroke:#ef4444,color:#fff\n    style E fill:#1e3a8a,stroke:#3b82f6,color:#fff\n    style F fill:#1e3a8a,stroke:#3b82f6,color:#fff\n    style G fill:#1e3a8a,stroke:#3b82f6,color:#fff\n    style H fill:#166534,stroke:#22c55e,color:#fff\n    style I fill:#166534,stroke:#22c55e,color:#fff\n    style J fill:#166534,stroke:#22c55e,color:#fff"}'::jsonb,
        '["Moradores", "SAMU", "Síndico", "Portaria Online"]'::jsonb,
        '{"telefone_samu": null, "ponto_encontro_ambulancia": null}'::jsonb
    ) INTO v_process_id;
    SELECT seed_single_process(
        'Alagamentos',
        'emergencias',
        'manual',
        'em_revisao',
        'Procedimento de emergência para situações de alagamento, incluindo proteção de equipamentos, drenagem e acionamento de serviços.',
        '{"description": "Procedimento de emergência para situações de alagamento, incluindo proteção de equipamentos, drenagem e acionamento de serviços.", "workflow": ["1. Identificação do alagamento", "2. Proteção de equipamentos elétricos", "3. Isolamento da área se possível", "4. Acionamento de serviços de drenagem se necessário", "5. Comunicação ao síndico/administradora", "6. Documentação fotográfica do dano", "7. Limpeza e secagem", "8. Verificação de danos estruturais", "9. Reparos necessários", "10. Registro do incidente e medidas preventivas"], "entities": ["Moradores", "Síndico", "Administradora", "Empresa de Manutenção"], "variables": ["telefone_emergencia"], "mermaid_diagram": "flowchart TD\n    A[\"Identificação do Alagamento<br/>(Moradores)\"] --> B[\"Proteção de Equipamentos Elétricos<br/>(Moradores)\"]\n    B --> C{Isolar Área Possível?}\n    C -->|Sim| D[\"Isolamento<br/>(Moradores)\"]\n    C -->|Não| E[\"Acionamento Drenagem<br/>(Síndico)\"]\n    D --> E\n    E --> F[\"Comunicação Síndico/Administradora<br/>(Moradores)\"]\n    F --> G[\"Documentação Fotográfica<br/>(Síndico)\"]\n    G --> H[\"Limpeza e Secagem<br/>(Empresa de Manutenção)\"]\n    H --> I[\"Verificação de Danos<br/>(Síndico)\"]\n    I --> J{Danos Estruturais?}\n    J -->|Sim| K[\"Reparos<br/>(Empresa de Manutenção)\"]\n    J -->|Não| L[\"Registro do Incidente<br/>(Administradora)\"]\n    K --> M[\"Medidas Preventivas<br/>(Síndico)\"]\n    M --> L\n    style A fill:#dc2626,stroke:#ef4444,color:#fff\n    style B fill:#dc2626,stroke:#ef4444,color:#fff\n    style D fill:#dc2626,stroke:#ef4444,color:#fff\n    style E fill:#dc2626,stroke:#ef4444,color:#fff\n    style F fill:#1e3a8a,stroke:#3b82f6,color:#fff\n    style G fill:#166534,stroke:#22c55e,color:#fff\n    style H fill:#1e3a8a,stroke:#3b82f6,color:#fff\n    style I fill:#166534,stroke:#22c55e,color:#fff\n    style K fill:#1e3a8a,stroke:#3b82f6,color:#fff\n    style L fill:#166534,stroke:#22c55e,color:#fff\n    style M fill:#166534,stroke:#22c55e,color:#fff"}'::jsonb,
        '["Moradores", "Síndico", "Administradora", "Empresa de Manutenção"]'::jsonb,
        '{"telefone_emergencia": null}'::jsonb
    ) INTO v_process_id;
END $$;