#!/bin/bash
# Script para configurar Neon como banco de dados na Vercel

echo "🗄️  Configuração do Neon para Villa Dei Fiori"
echo ""
echo "📋 Passo a Passo:"
echo ""
echo "1. Criar conta no Neon:"
echo "   https://neon.tech"
echo ""
echo "2. Criar projeto:"
echo "   - Nome: villadelfiori"
echo "   - Região: escolha a mais próxima"
echo "   - PostgreSQL: versão 15 ou 16"
echo ""
echo "3. Copiar connection string:"
echo "   - Dashboard → Connection Details"
echo "   - Copie a connection string (formato: postgresql://...)"
echo ""
echo "4. Configurar na Vercel:"
echo "   vercel env add DATABASE_URL production"
echo "   # Cole a connection string quando solicitado"
echo ""
echo "5. Executar migrations:"
echo "   curl -X POST https://seu-dominio.vercel.app/v1/admin/run-migrations"
echo ""
echo "6. Criar usuário admin:"
echo "   curl -X POST https://seu-dominio.vercel.app/v1/admin/create-admin"
echo ""
echo "✅ Pronto! O banco estará configurado."
echo ""
echo "📝 Veja OPCOES_BANCO_VERCEL.md para mais detalhes"

